import { EditorView } from "@codemirror/view";
import { HighlightStyle } from "@codemirror/language";
import { tags as t } from "@lezer/highlight";

/** The editor's chrome. Every colour is one of the app's tokens (see --editor-* and --syn-* in
 *  styles.css), so it follows the light and dark themes without being rebuilt. */
export const editorChrome = EditorView.theme({
  "&": {
    height: "100%",
    color: "var(--text)",
    backgroundColor: "var(--editor-bg)",
    fontSize: "13.5px",
  },
  "&.cm-focused": { outline: "none" },
  ".cm-scroller": {
    fontFamily: "var(--font-mono)",
    lineHeight: "1.65",
    fontVariantLigatures: "none",
  },
  ".cm-content": { padding: "10px 0 40vh", caretColor: "var(--accent)" },
  ".cm-line": { padding: "0 24px 0 8px" },
  ".cm-cursor, .cm-dropCursor": { borderLeft: "2px solid var(--accent)" },
  "&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection":
    { backgroundColor: "var(--editor-selection) !important" },
  ".cm-activeLine": { backgroundColor: "var(--editor-line)" },
  ".cm-gutters": {
    backgroundColor: "var(--editor-bg)",
    color: "var(--editor-gutter)",
    border: "none",
  },
  ".cm-lineNumbers .cm-gutterElement": { minWidth: "44px", padding: "0 6px 0 14px" },
  ".cm-activeLineGutter": { backgroundColor: "transparent", color: "var(--text)" },
  ".cm-foldGutter .cm-gutterElement": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "18px",
    color: "var(--editor-gutter)",
    cursor: "pointer",
  },
  ".cm-foldGutter .cm-gutterElement:hover": { color: "var(--text)" },
  ".cm-foldPlaceholder": {
    margin: "0 4px",
    padding: "0 6px",
    border: "none",
    borderRadius: "4px",
    backgroundColor: "var(--raised)",
    color: "var(--text-muted)",
  },
  ".cm-matchingBracket, &.cm-focused .cm-matchingBracket": {
    backgroundColor: "var(--editor-bracket)",
    outline: "1px solid var(--editor-bracket-edge)",
    borderRadius: "2px",
  },
  ".cm-nonmatchingBracket, &.cm-focused .cm-nonmatchingBracket": { backgroundColor: "var(--danger-soft)" },
  ".cm-selectionMatch": { backgroundColor: "var(--editor-match)" },
  ".cm-searchMatch": {
    backgroundColor: "var(--editor-search)",
    outline: "1px solid var(--editor-search-edge)",
    borderRadius: "2px",
  },
  ".cm-searchMatch.cm-searchMatch-selected": { backgroundColor: "var(--editor-search-current)" },
  ".cm-specialChar": { color: "var(--danger-text)" },
  ".cm-trailingSpace": { backgroundColor: "var(--danger-soft)" },

  // Find and replace (Ctrl+F), styled like the rest of the app.
  ".cm-panels": { backgroundColor: "var(--sidebar)", color: "var(--text)" },
  ".cm-panels.cm-panels-bottom": { borderTop: "1px solid var(--line)" },
  ".cm-panels.cm-panels-top": { borderBottom: "1px solid var(--line)" },
  ".cm-search": {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "6px",
    padding: "8px 40px 8px 14px",
    fontFamily: "var(--font-ui)",
    fontSize: "12.5px",
  },
  ".cm-search br": { flexBasis: "100%", height: 0 },
  ".cm-textfield": {
    height: "28px",
    margin: 0,
    padding: "0 9px",
    border: "1px solid var(--line)",
    borderRadius: "6px",
    backgroundColor: "var(--field)",
    color: "var(--text)",
    fontFamily: "var(--font-mono)",
    fontSize: "12.5px",
  },
  ".cm-textfield:focus": { borderColor: "var(--accent)", outline: "none" },
  ".cm-button": {
    height: "28px",
    margin: 0,
    padding: "0 10px",
    border: "1px solid var(--line)",
    borderRadius: "6px",
    backgroundImage: "none",
    backgroundColor: "var(--raised)",
    color: "var(--text)",
    fontFamily: "var(--font-ui)",
    fontSize: "12.5px",
    fontWeight: "600",
    textTransform: "capitalize",
  },
  ".cm-button:hover": { backgroundColor: "var(--raised-hover)" },
  ".cm-button:active": { backgroundImage: "none" },
  ".cm-search label": {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    color: "var(--text-muted)",
    fontSize: "12.5px",
    textTransform: "capitalize",
  },
  ".cm-search input[type=checkbox]": { margin: 0, accentColor: "var(--accent)" },
  ".cm-panel.cm-search [name=close]": {
    top: "8px",
    right: "10px",
    width: "26px",
    height: "26px",
    borderRadius: "6px",
    color: "var(--text-muted)",
    fontSize: "18px",
    lineHeight: "24px",
  },
  ".cm-panel.cm-search [name=close]:hover": { backgroundColor: "var(--raised-hover)", color: "var(--text)" },

  ".cm-tooltip": {
    border: "1px solid var(--line)",
    borderRadius: "8px",
    backgroundColor: "var(--dialog)",
    color: "var(--text)",
  },
});

/** Code colours, by what each piece of the code is. */
export const codeColours = HighlightStyle.define([
  { tag: [t.keyword, t.controlKeyword, t.moduleKeyword, t.operatorKeyword, t.definitionKeyword, t.modifier], color: "var(--syn-keyword)" },
  { tag: [t.self, t.special(t.variableName)], color: "var(--syn-keyword)", fontStyle: "italic" },
  { tag: [t.string, t.character, t.attributeValue, t.docString], color: "var(--syn-string)" },
  { tag: [t.regexp, t.escape, t.special(t.string)], color: "var(--syn-regexp)" },
  { tag: [t.number, t.integer, t.float, t.bool, t.null, t.atom, t.unit], color: "var(--syn-number)" },
  { tag: [t.comment, t.lineComment, t.blockComment, t.docComment], color: "var(--syn-comment)", fontStyle: "italic" },
  {
    tag: [t.function(t.variableName), t.function(t.propertyName), t.function(t.definition(t.variableName)), t.macroName],
    color: "var(--syn-function)",
  },
  { tag: [t.typeName, t.className, t.namespace, t.standard(t.typeName), t.definition(t.typeName)], color: "var(--syn-type)" },
  { tag: [t.propertyName, t.attributeName, t.definition(t.propertyName), t.labelName], color: "var(--syn-property)" },
  { tag: [t.tagName, t.angleBracket], color: "var(--syn-tag)" },
  { tag: [t.constant(t.variableName), t.standard(t.variableName)], color: "var(--syn-number)" },
  { tag: [t.operator, t.derefOperator, t.punctuation, t.separator, t.bracket], color: "var(--syn-punct)" },
  { tag: [t.meta, t.annotation, t.processingInstruction, t.documentMeta], color: "var(--syn-meta)" },
  { tag: t.heading, color: "var(--syn-heading)", fontWeight: "700" },
  { tag: t.emphasis, fontStyle: "italic" },
  { tag: t.strong, fontWeight: "700" },
  { tag: t.strikethrough, textDecoration: "line-through" },
  { tag: t.link, color: "var(--syn-function)", textDecoration: "underline" },
  { tag: t.url, color: "var(--syn-string)" },
  { tag: t.inserted, color: "var(--added)" },
  { tag: t.deleted, color: "var(--deleted)" },
  { tag: t.changed, color: "var(--modified)" },
  { tag: t.invalid, color: "var(--danger-text)" },
]);
